# This is a config for E2B sandbox template.
# You can use template ID (n4isgex9487pm0jli9i0) or template name (cube-r2adio) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("cube-r2adio") # Sync sandbox
# sandbox = await AsyncSandbox.create("cube-r2adio") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('cube-r2adio')

team_id = "7cbbfd4a-5abc-44fe-95ac-7bbb51bd50c9"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "cube-r2adio"
template_id = "n4isgex9487pm0jli9i0"
